### ISSUE TITLE
Registered ETH address

### ISSUE THREAD

**Issue by relapsing** [SynapseOrg/neuron-releases#2]
The ETH address in my Neuron Wallet (MS) is different than the Neureon ETH address in my SYN account on the website.

Neuron: 
![image](https://user-images.githubusercontent.com/32651759/45008493-0c0cef00-afd1-11e8-808d-2bc038867641.png)

SYN account: 
![image](https://user-images.githubusercontent.com/32651759/45008579-6ad26880-afd1-11e8-8181-b556e54b3dd2.png)

**Comment by amin137954** [comment]
چطور دستیابی پیدا کنم؟

**Comment by tiknores** [comment]
0x15E97e77badE4B3E9EC69F49d1e9c55e9B7b85f2

**Comment by titopop66666** [comment]
0x0c8831A521651dfDb3e2F0Bcb2FcbDBDb414e837
